version: "3"

services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"

  redis:
    image: redis:3.2  # No higher than Elasticache latest
    ports:
      - "6379:6379"

  stripe:
    build:
      context: https://github.com/stripe/stripe-mock.git
    ports:
      - "12111:12111"

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: "firehose,kinesis,lambda,s3,sqs"
    ports:
      - "4567-4583"

  frontend:
    image: node:9-stretch
    command: sh -c 'yarn && yarn dev'
    volumes:
      - "./HSReplay.net:/opt/hsreplay.net/source"
    working_dir: /opt/hsreplay.net/source
    environment:
      NODE_ENV: "development"
    ports:
      - "3000:3000"

  django:
    build: .
    command: sh -c 'pipenv run ./manage.py runserver 0.0.0.0:8000'
    volumes:
      - "./HSReplay.net:/opt/hsreplay.net/source"
    working_dir: /opt/hsreplay.net/source
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      PIPENV_VENV_IN_PROJECT: "1"
    depends_on:
      - db
      - localstack
      - redis
      - stripe
