version: "3.2"

services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"

  redis:
    image: redis:3.2  # No higher than Elasticache latest
    ports:
      - "6379:6379"

  stripe:
    build:
      context: https://github.com/stripe/stripe-mock.git
    ports:
      - "12111:12111"

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: "firehose,kinesis,lambda,s3,sqs"
    ports:
      - "4567-4583"

  frontend:
    image: node:9-stretch
    command: sh -c 'yarn && yarn dev'
    volumes:
      - type: bind
        source: "./HSReplay.net"
        target: "/opt/hsreplay.net/source"
    working_dir: /opt/hsreplay.net/source
    ports:
      - "3000:3000"

  django:
    build: .
    volumes:
      - type: bind
        source: "./HSReplay.net"
        target: "/opt/hsreplay.net/source"
    working_dir: /opt/hsreplay.net/source
    ports:
      - "8000:8000"
    environment:
      AWS_DEFAULT_REGION: "us-east-1"
      DJANGO_SETTINGS_MODULE: "hsreplaynet.settings"
    depends_on:
      - db
      - localstack
      - redis
      - stripe
